using System;
using System.IO;
using System.Text;

using IniParser.Model;
using IniParser.Model.Formatting;
using IniParser.Parser;


namespace DoomMapGuessr.Settings
{

	/// <summary>
	/// Settings for an application.
	/// </summary>
	/// <param name="directoryPath">The directory of the settings</param>
    public sealed class ApplicationSettings(
        string directoryPath
    ) : IEquatable<ApplicationSettings>
    {

		/// <summary>
		/// The directory for this app's settings.
		/// </summary>
        public string DirectoryPath { get; } = directoryPath;

		/// <summary>
		/// The actual settings, in INI format.
		/// </summary>
        public IniData Data { get; private set; } = new();

		/// <summary>
		/// Creates a settings subdirectory.
		/// </summary>
        public void CreateDirectory() => Directory.CreateDirectory(DirectoryPath);

        /// <inheritdoc />
        public bool Equals(ApplicationSettings? other)
        {

            if (other is null)
                return false;

            if (ReferenceEquals(this, other))
                return true;

            return DirectoryPath == other.DirectoryPath;

        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {

            if (obj is null)
                return false;

            if (ReferenceEquals(this, obj))
                return true;

            return obj.GetType() == GetType() && Equals((ApplicationSettings)obj);

        }

        /// <inheritdoc />
        public override int GetHashCode() => DirectoryPath.GetHashCode();

		/// <summary>
		/// Saves the settings to a file that can be outside the actual
		/// settings directory.
		/// </summary>
		/// <param name="filename">The path to the file</param>
        public void Save(string filename) => SetConfigFile(filename, Data);

        /// <inheritdoc />
        public override string ToString() => $"{nameof(DirectoryPath)}: {DirectoryPath}";

		/// <summary>
		/// Gets a config file by its name.
		/// </summary>
		/// <param name="name">The config file's nameparam>
		/// <param name="defaults">THe default data to fill in in case the file is missing</param>
		/// <returns>The settings data, as INI</returns>
        private IniData GetConfigFile(string name, IniData? defaults = null)
        {

            string path = Path.Join(DirectoryPath, $"{name}.ini");

            if (!File.Exists(path))
            {

                if (defaults is null)
                    File.WriteAllText(Path.Join(DirectoryPath, $"{name}.ini"), "; This file was generated by DoomMapGuessr");

                else
                    SetConfigFile(name, defaults);

            }

            IniDataParser parser = new(
                new()
                {
                    AllowCreateSectionsOnFly = true,
                    AllowDuplicateKeys = true,
                    OverrideDuplicateKeys = true,
                    ThrowExceptionsOnError = false
                }
            );

            return parser.Parse(File.ReadAllText(path, Encoding.UTF8));

        }

		/// <summary>
		/// Prepares the directory for the default usage of this class.
		/// Recommended if you do not know how to use this class
		/// or if you simply want quick setup.<br/>
		/// It is also recommended to not use this directly and instead use
		/// <see cref="ApplicationState.Shared"/> for an even faster setup.
		/// </summary>
		/// <returns>The prepared settings</returns>
        public ApplicationSettings PrepareDirectoryForDefaultUsage()
        {

            CreateDirectory();
            Data = GetConfigFile("config");

            return this;

        }

		/// <summary>
		/// Saves or adds a config file.
		/// </summary>
		/// <param name="name">The file's name</param>
		/// <param name="resources">The resources, as INI, to fill it with</param>
        private void SetConfigFile(string name, IniData resources)
        {

            string path = Path.Join(DirectoryPath, $"{name}.ini");

            string? ini = resources.ToString(
                new DefaultIniDataFormatter(
                    new()
                    {
                        AllowCreateSectionsOnFly = true,
                        AllowDuplicateKeys = true,
                        OverrideDuplicateKeys = true,
                        ThrowExceptionsOnError = false
                    }
                )
            );

            File.WriteAllText(path, ini, Encoding.UTF8);

        }

		/// <summary>
		/// Checks if two instances of 
		/// <see cref="ApplicationSettings"/>
		/// are <strong>equals</strong>.
		/// </summary>
		/// <param name="left"></param>
		/// <param name="right"></param>
		/// <returns></returns>
		public static bool operator ==(ApplicationSettings? left, ApplicationSettings? right) => Equals(left, right);

		/// <summary>
		/// Checks if two instances of 
		/// <see cref="ApplicationSettings"/>
		/// are <strong>different</strong>.
		/// </summary>
		/// <param name="left"></param>
		/// <param name="right"></param>
		/// <returns></returns>
		public static bool operator !=(ApplicationSettings? left, ApplicationSettings? right) => !Equals(left, right);

    }

}
