using System;
using System.IO;
using System.Reflection;
using System.Text;

using IniParser.Model;
using IniParser.Model.Formatting;
using IniParser.Parser;


namespace DoomMapGuessr.Services
{

    public sealed class ApplicationSettings(
        string directoryPath
    ) : IEquatable<ApplicationSettings>
    {

        public static Version? AssemblyVersion => Assembly.GetEntryAssembly()?.GetName().Version;

        public static string? AppVersion => AssemblyVersion is null ? null : $"{AssemblyVersion.Major}{AssemblyVersion.Minor}{AssemblyVersion.Build}";

        public static ApplicationSettings Shared { get; } = new ApplicationSettings(
            Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "dev.mf366.DoomMapGuessr")
        ).PrepareDirectory();

        public ApplicationCache? Cache { get; internal set; }

        public string DirectoryPath { get; } = directoryPath;

        public IniData Settings { get; private set; } = new();

        public ApplicationCache? Temp { get; internal set; }

        public void Clear()
        {

            Cache?.Clear();
            Temp?.Clear();

        }


        public void CreateDirectory() => Directory.CreateDirectory(DirectoryPath);

        /// <inheritdoc />
        public bool Equals(ApplicationSettings? other)
        {

            if (other is null)
                return false;

            if (ReferenceEquals(this, other))
                return true;

            return DirectoryPath == other.DirectoryPath;

        }

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {

            if (obj is null)
                return false;

            if (ReferenceEquals(this, obj))
                return true;

            return obj.GetType() == GetType() && Equals((ApplicationSettings)obj);

        }

        /// <inheritdoc />
        public override int GetHashCode() => DirectoryPath.GetHashCode();

        public void Save(string filename) => SetConfigFile(filename, Settings);

        /// <inheritdoc />
        public override string ToString() => $"{nameof(DirectoryPath)}: {DirectoryPath}";

        private void CreateCacheAndTemp()
        {

            Cache = new(this);
            Temp = new(this, "TempFiles");

        }

        private IniData GetConfigFile(string name, IniData? defaults = null)
        {

            string path = Path.Join(DirectoryPath, $"{name}.ini");

            if (!File.Exists(path))
            {

                if (defaults is null)
                    File.WriteAllText(Path.Join(DirectoryPath, $"{name}.ini"), "; This file was generated by DoomMapGuessr");

                else
                    SetConfigFile(name, defaults);

            }

            IniDataParser parser = new(
                new()
                {
                    AllowCreateSectionsOnFly = true,
                    AllowDuplicateKeys = true,
                    OverrideDuplicateKeys = true,
                    ThrowExceptionsOnError = false
                }
            );

            return parser.Parse(File.ReadAllText(path, Encoding.UTF8));

        }

        private ApplicationSettings PrepareDirectory()
        {

            CreateDirectory();
            CreateCacheAndTemp();
            Settings = GetConfigFile("config");

            return this;

        }

        private void SetConfigFile(string name, IniData resources)
        {

            string path = Path.Join(DirectoryPath, $"{name}.ini");

            string? ini = resources.ToString(
                new DefaultIniDataFormatter(
                    new()
                    {
                        AllowCreateSectionsOnFly = true,
                        AllowDuplicateKeys = true,
                        OverrideDuplicateKeys = true,
                        ThrowExceptionsOnError = false
                    }
                )
            );

            File.WriteAllText(path, ini, Encoding.UTF8);

        }

        public static bool operator ==(ApplicationSettings? left, ApplicationSettings? right) => Equals(left, right);

        public static bool operator !=(ApplicationSettings? left, ApplicationSettings? right) => !Equals(left, right);

    }

}
