//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoomMapGuessr.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoomMapGuessr.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements &amp; Items.
        /// </summary>
        public static string AchievementsUnlockables {
            get {
                return ResourceManager.GetString("AchievementsUnlockables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF366 (Matthew).
        /// </summary>
        public static string App_CreatorName {
            get {
                return ResourceManager.GetString("App_CreatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GeoGuessr of Doom..
        /// </summary>
        public static string App_Slogan {
            get {
                return ResourceManager.GetString("App_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoomMapGuessr.
        /// </summary>
        public static string App_TitleName {
            get {
                return ResourceManager.GetString("App_TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Mode.
        /// </summary>
        public static string ClassicMode {
            get {
                return ResourceManager.GetString("ClassicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy of Rust joins the alignment!.
        /// </summary>
        public static string Flavor_InclusionOfLegacyOfRust {
            get {
                return ResourceManager.GetString("Flavor_InclusionOfLegacyOfRust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest WAD to be developed by id Software joins the alignment of guessable WADs in this major DoomMapGuessr update!
        ///What are you waiting for?
        ///Start guessing now!.
        /// </summary>
        public static string Flavor_InclusionOfLegacyOfRust_Description {
            get {
                return ResourceManager.GetString("Flavor_InclusionOfLegacyOfRust_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Items.
        /// </summary>
        public static string Flavor_Unlockables {
            get {
                return ResourceManager.GetString("Flavor_Unlockables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch your achievements turn into items!
        ///The more you play, the more you get!
        ///From backgrounds to game modes, it&apos;s rip and tear until it is done..
        /// </summary>
        public static string Flavor_Unlockables_Description {
            get {
                return ResourceManager.GetString("Flavor_Unlockables_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoGuessr Mode.
        /// </summary>
        public static string GeoMode {
            get {
                return ResourceManager.GetString("GeoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection available.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Interface.
        /// </summary>
        public static string Settings_AppInterface {
            get {
                return ResourceManager.GetString("Settings_AppInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        public static string Settings_AspectRatio {
            get {
                return ResourceManager.GetString("Settings_AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Proportions.
        /// </summary>
        public static string Settings_AspectRatio_MaintainProportions {
            get {
                return ResourceManager.GetString("Settings_AspectRatio_MaintainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achromatopsia (monochromacy).
        /// </summary>
        public static string Settings_Color_Achromatopsia {
            get {
                return ResourceManager.GetString("Settings_Color_Achromatopsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuteranopia (green-blindness).
        /// </summary>
        public static string Settings_Color_Deuteranopia {
            get {
                return ResourceManager.GetString("Settings_Color_Deuteranopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Color.
        /// </summary>
        public static string Settings_Color_MaintainColor {
            get {
                return ResourceManager.GetString("Settings_Color_MaintainColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protanopia (red-blindness).
        /// </summary>
        public static string Settings_Color_Protanopia {
            get {
                return ResourceManager.GetString("Settings_Color_Protanopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritanopia (blue-blindness).
        /// </summary>
        public static string Settings_Color_Tritanopia {
            get {
                return ResourceManager.GetString("Settings_Color_Tritanopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay Screenshots.
        /// </summary>
        public static string Settings_DoomScreenshots {
            get {
                return ResourceManager.GetString("Settings_DoomScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Source Blacklist.
        /// </summary>
        public static string Settings_DoomScreenshots_SourcesBlacklist {
            get {
                return ResourceManager.GetString("Settings_DoomScreenshots_SourcesBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string Settings_GUI_ThemingDarkMode {
            get {
                return ResourceManager.GetString("Settings_GUI_ThemingDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom theme.
        /// </summary>
        public static string Settings_GUI_UseCustomTheme {
            get {
                return ResourceManager.GetString("Settings_GUI_UseCustomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string Settings_Language_FollowSystem {
            get {
                return ResourceManager.GetString("Settings_Language_FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language:.
        /// </summary>
        public static string Settings_Language_InputFieldTitle {
            get {
                return ResourceManager.GetString("Settings_Language_InputFieldTitle", resourceCulture);
            }
        }
    }
}
